
default_platform(:android)

platform :android do
  desc "Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:1055515917924:android:8dab76429e483097dca971",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "fadyalaa441@gmail.com, fadyalaa2112@gmail.com",
      upload_timeout: 600,
      release_notes: "1.0.7 version release notes: 
      -finished friend request logic and accept or reject requests waiting for test review",
    )
  end
end 